language: python

python:
  - 2.7

services: postgresql

env:
  - DJANGO=1.8.1

before_install:
  - export DJANGO_SETTINGS_MODULE=scblog.settings
 # - export PYTHONPATH=$HOME/builds/your_github_username/your_repo
 # - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE scblog_db;" -U postgres

script:
  - python manage.py migrate
